name: Docker Image CI

on: [ push,  pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: | 
        cd ./client
        docker build . --file client.dockerfile --tag jskonst/web-app:client
    - name: Docker push
      run: |
        docker push jskonst/web-app:client
