name: Docker Image CI

on: [ push,  pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image      
      run: | 
        cd ./server
        docker build . --file server.dockerfile --tag jskonst/web-app:server
    - name: Docker push
      run: |
        docker push jskonst/web-app:server
